services:
  - type: web
    name: dronzer-urlshortener
    env: nixpacks
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/*.jar"
    autoDeploy: true
    plan: free
